### PR TITLE
Switch to using GitHub API for less resource usage and faster following/unfollowing

### PR DESCRIPTION
**Pull request by M4cs**
- Adds GitHub API Methods
- Faster Following/Unfollowing
- Stores users to a JSON file
- Allows for following/unfollowing from a JSON file

### CODE REVIEW

**Comment by Anteste** [comment]
Oh Awesome :) , I' m checking your code and I will merge it if it's working

**Comment by M4cs** [comment]
I should add some part about obtaining a personal access token, it requires the `user:follow` scope

**Comment by M4cs** [comment]
Added information about obtaining a Personal Access Token

**Comment by M4cs** [comment]
What are the odds for somebody forking, starring, and pull requesting? 😉

**Comment by Anteste** [comment]
Your code is perfect I will merge it, but we will have to make a small change about the unfollow function because how can we get all the users in a File to unfollow them ? we must write them manualy and it will take an eternity.
can you make it like that ?
```python unfollow_bot.py -t <PERSONAL_ACCESS_TOKEN> -m <YOUR_USERNAME>```

**Comment by Anteste** [comment]
> What are the odds for somebody forking, starring, and pull requesting? 😉

the chances are very low
thank you for contributing in this project

**Pull request merged**
